services:
  - type: web
    name: playwright-api
    env: node
    buildCommand: |
      npm install
      npx playwright install --with-deps
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
